# Generated by Django 4.1.7 on 2023-03-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='my_store_app/static/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(null=True, upload_to='my_store_app/static/'),
        ),
    ]
