# Generated by Django 4.1.7 on 2023-04-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0004_basket_quantity_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='my_store_app.product'),
        ),
    ]
