# Generated by Django 4.1.7 on 2023-04-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0005_remove_basket_product_basket_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='username',
            new_name='customer',
        ),
    ]
