# Generated by Django 4.1.7 on 2023-04-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0007_remove_basket_customer_basket_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='my_store_app.profile'),
        ),
    ]
