# Generated by Django 4.1.7 on 2023-04-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0009_alter_basket_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='my_store_app.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='my_store_app.profile')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
