# Generated by Django 4.1.7 on 2023-06-05 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0013_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='my_store_app.product', verbose_name='товар'),
        ),
    ]
