# Generated by Django 4.1.7 on 2023-06-05 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_store_app', '0015_alter_order_delivery_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
