# Generated by Django 4.1.7 on 2023-06-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0016_productinorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
